sudo: required
dist: trusty

cache:
    ccache: true
    apt: true
    directories:
        - gcc-infrastructure

language: c

before_install:
    - sudo apt-get install -qq
      build-essential
    - sudo apt-get install -qq
      bison
      flex
      g++-arm-linux-gnueabihf
      gcc-arm-linux-gnueabihf
      libgmp3-dev
      libncurses5-dev
      libmpc-dev
      libmpfr-dev
      locate
      texinfo
      wget

script:
    - ./sdk/download-components.sh --download
    - ./.travis.sh

